# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-02 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('author', models.CharField(max_length=20)),
                ('slug', models.SlugField(max_length=10)),
                ('content', models.TextField(max_length=1000)),
                ('status', models.CharField(choices=[('PB', 'Published'), ('DF', 'Draft')], max_length=15)),
            ],
        ),
    ]
