# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-08-02 23:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application1', '0002_auto_20190802_1600'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='content',
            new_name='PageContent',
        ),
    ]
